config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: postgres
      host: database-1.c4yrc1ftvd9q.us-east-1.rds.amazonaws.com
      pass: nisha123
      port: 5432
      schema: public
      threads: 8
      type: postgres
      user: postgres
  target: prod
